# Generated by Django 2.1.2 on 2019-03-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='note',
            field=models.TextField(max_length=256),
        ),
    ]
