# Generated by Django 2.1.2 on 2019-03-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190302_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='note',
            field=models.TextField(),
        ),
    ]
